services:
  car_booking_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
        - PORT=3000
        - NODE_ENV=development
        - DATABASE_URL=mysql://testuser:testuserpassword@mysql_db:3306/car_booking
    volumes:
      - ./src:/usr/src/app/src

  mysql_db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_booking
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuserpassword
      MYSQL_TCP_PORT: '3306'